export default function TermsPage() {
  return (
    <div className="max-w-2xl mx-auto py-10 px-4">
      <h1 className="text-3xl font-black tracking-tighter mb-2">Terms of Service</h1>
      <p className="text-zinc-500 text-sm mb-8">Last updated: March 7, 2025</p>

      <div className="space-y-6 text-zinc-300 text-sm leading-relaxed">
        <section>
          <h2 className="text-lg font-bold text-white mb-2">Use of the Service</h2>
          <p>AISlop Hub is a platform for sharing and rating AI-generated content. By using this site, you agree not to submit content that is illegal, harassing, or violates the rights of others.</p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-white mb-2">Your Content</h2>
          <p>You retain ownership of content you submit. By submitting, you grant AISlop Hub a non-exclusive license to display it on the platform. You are responsible for ensuring you have the right to share any content you submit.</p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-white mb-2">Prohibited Content</h2>
          <p>Do not submit content that is hateful, sexually explicit, or designed to harass individuals. We reserve the right to remove content and suspend accounts that violate these rules.</p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-white mb-2">AI Judgments</h2>
          <p>Slop scores and roasts are generated by AI and are intended for entertainment purposes only. They do not reflect the views of AISlop Hub and should not be taken as professional assessments.</p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-white mb-2">Disclaimer</h2>
          <p>This service is provided as-is. We make no guarantees of uptime, accuracy, or fitness for any particular purpose.</p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-white mb-2">Changes</h2>
          <p>We may update these terms from time to time. Continued use of the platform constitutes acceptance of any changes.</p>
        </section>

        <section>
          <h2 className="text-lg font-bold text-white mb-2">Contact</h2>
          <p>Questions? Email <a href="mailto:alihhamie@gmail.com" className="text-yellow-400 hover:underline">alihhamie@gmail.com</a>.</p>
        </section>
      </div>
    </div>
  );
}
